### ISSUE TITLE
Class timetable for both homepage and classes pages is consistent while psd design has different designs. Is it possible to have two timetable for each page? Or just only one table for each page. 

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolution-MMA#134]

**Comment by christiancebudigital** [comment]
Hi Erma,

Will make this one consistent, since they have same data, we don't want the user to be confused on the information given in the class timetable, but yes it is possible to have multiple class timetable in one page, let me know your thoughts.

Thanks,
Christian

**Comment by ermatitan** [comment]
Hello Christian, 
As suggested by Bernard, maybe it would be better to rename the Event ACF to Class ACF to avoid confusion to the part of the client since all event are referring to a class schedule among trainers. Thanks

![image](https://cloud.githubusercontent.com/assets/12791909/10038673/5f56dc1a-61fb-11e5-8b8c-4e640930b7ee.png)

**Comment by christiancebudigital** [comment]
HI Erma,

I think this is not possible, this is Event Custom post type, and the event is also generated by the class timetable plugin, we are not allowed to touch backend code, we think this is named events because this is used to get data event within a specific day, this is also linked to the timetable columns, let me know you thoughts.

Thanks,
Christian

**Comment by ermatitan** [comment]
Hello Christian, 

You just have to rename the Event  to Classes, no need to touch the back end code as per Bernard comment. This is also for consistency on the Event single page to match the url/permalink to its breadcrumbs.

Thanks, 
Erma

![image](https://cloud.githubusercontent.com/assets/12791909/10066907/03be1bf0-62ca-11e5-9d6f-468e465bd3cf.png)

**Comment by christiancebudigital** [comment]
Hi Erma,

as ive said in my Previous post, this is plugin generated, if you have an idea on how to change the permalink on events custom plugin, without changing the backend code, let me know, because as far as i know, we need to touch its backend, since this is related to its core plugin.

Thanks,
Christian
