### ISSUE TITLE
Sidebar and Footer Gravity Form - error message disappears when mouse hover

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolution-MMA#139]
![image](https://cloud.githubusercontent.com/assets/12791909/10038722/1d54fa62-61fc-11e5-9341-d7871c0bfcae.png)

**Comment by christiancebudigital** [comment]
Hi Erma,

Sidebar hover is now fixed, but with regards with the gravity forms in footer area, we made the error be fadeable on hover because it will distort the page of the footer, when validated, the box is height is just limited, so made it fade on hover, let me know your thoughts.

Thanks,
Christian

**Comment by ermatitan** [comment]
Sidebar gravity form fix. Cannot verify the footer area due to error #148
