### ISSUE TITLE
Mobile: Class Timetable not functioning properly smaller devices

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolution-MMA#79]
Samsung Tab 3, S4 , iTouch

![image](https://cloud.githubusercontent.com/assets/12791909/9726040/ef3694ca-561f-11e5-9b44-01d5ef868788.png)

**Comment by christiancebudigital** [comment]
Hi Erma,

This is working well, this is the functionality of the class timetable, when viewing it responsively, you may verify this link [ http://quanticalabs.com/script/timetable-responsive-schedule-for-wordpress/7010836 ] because this is what the client want based on the design brief given, let me know if you have question.

Cheers,
Christian

**Comment by ermatitan** [comment]
This functionality is not specified in the project scope that is why it log as a bug. Please add this to project scope. Thanks

**Comment by christiancebudigital** [comment]
Hi  Erma,

THis is specified in project scope, under #12Classes, in the Reference column, see PS.
[ https://docs.google.com/spreadsheets/d/1hICIP7GD3_Ik7mRpleO7lMabbAvFXCHTzpxZDhV0j9E/edit#gid=2035631399 ]

Thank,
Christian
